---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by avikulin.
--- DateTime: 19.03.2024 13:53
---

local X_COORD_QUERY_PARAM<const> = "longitude"
local Y_COORD_QUERY_PARAM<const> = "latitude"

local weather_provider = require('app.src.open_weather_client')
local weather_provider_metadata = require('app.src.open_weather_client_metadata')

-- Примеры поддерживаемых запросов:
-- http://localhost:8081/weather/current?latitude=...&longitude=...
-- http://localhost:8081/weather/hourly?latitude=...&longitude=...
-- http://localhost:8081/weather/daily?latitude=...&longitude=...
local function get_weather(request_data)
    local global_cfg = cartridge.config_get_deepcopy()
    local weather_cfg = global_cfg[ROOT_CONFIG_KEY]

    local open_weather_client = weather_provider:new(
        weather_cfg[weather_provider_metadata.get_uri_cfg_key()],
        weather_cfg[weather_provider_metadata.get_longitude_cfg_key()],
        weather_cfg[weather_provider_metadata.get_latitude_cfg_key()],
        weather_cfg[weather_provider_metadata.get_actuality_opts_cfg_key()],
        weather_cfg[weather_provider_metadata.get_query_opts_cfg_key()]
    )

    -- обрезаем "weather/"

    local actuality = string.sub(request_data.path, 1, string.len(weather_provider_metadata.get_route_home_path()))
    local x_coord = request_data:query_param(X_COORD_QUERY_PARAM)
    local y_coort = request_data:query_param(Y_COORD_QUERY_PARAM)

    return weather_provider:get_weather_info(x_coord, y_coort, actuality)
end

return {
    get_weather = get_weather
}
