---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by andreyv.
--- DateTime: 20.03.2024 23:59
---

local CONFIG_CACHE_ROOT_KEY = "cache-dal"
local CONFIG_CACHE_SIZE_KEY = "size"
local CONFIG_CACHE_STRATEGY_KEY = "eviction_strategy"
local CONFIG_CACHE_TTL_KEY = "time-to-live"
local POLICY_LRU_NAME = "lru"
local POLICY_LRA_NAME = "lra"
local POLICY_FIFO_NAME = "fifo"
local AVAILABLE_EVICTION_STRATEGIES = {
                                            string.upper(POLICY_LRU_NAME),
                                            string.upper(POLICY_LRA_NAME),
                                            string.upper(POLICY_FIFO_NAME)
}

local function get_cfg_root_key()
    return CONFIG_CACHE_ROOT_KEY
end

local function get_cfg_cache_size_key()
    return CONFIG_CACHE_SIZE_KEY
end

local function get_cfg_cache_strategy_key()
    return CONFIG_CACHE_STRATEGY_KEY
end

local function get_cfg_ttl_key()
    return CONFIG_CACHE_TTL_KEY
end

local function get_available_eviction_strategies()
    return AVAILABLE_EVICTION_STRATEGIES
end

local function get_cfg_lru_policy_name()
    return POLICY_LRU_NAME
end

local function get_cfg_lra_policy_name()
    return POLICY_LRA_NAME
end

local function get_cfg_fifo_policy_name()
    return POLICY_FIFO_NAME
end

return {
    get_available_eviction_strategies = get_available_eviction_strategies,
    get_cfg_cache_strategy_key = get_cfg_cache_strategy_key,
    get_cfg_cache_size_key = get_cfg_cache_size_key,
    get_cfg_fifo_policy_name = get_cfg_fifo_policy_name,
    get_cfg_lra_policy_name = get_cfg_lra_policy_name,
    get_cfg_lru_policy_name = get_cfg_lru_policy_name,
    get_cfg_ttl_key = get_cfg_ttl_key,
    get_cfg_root_key = get_cfg_root_key
}
