---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by avikulin.
--- DateTime: 19.03.2024 20:35
---
local CONFIG_URI_KEY = "uri"
local CONFIG_X_COORD = "x_coord_param"
local CONFIG_Y_COORD = "y_coord_param"
local CONFIG_ACTUALITY_OPTS = "actuality_options"
local CONFIG_QUERY_OPTIONS = "query_options"
local URI_ROUTE_HOME_PATH = "/weather/"
local ROOT_CONFIG_KEY = "weather-provider"

local function get_uri_cfg_key()
    return CONFIG_URI_KEY
end

local function get_latitude_cfg_key()
    return CONFIG_Y_COORD
end

local function get_longitude_cfg_key()
    return CONFIG_X_COORD
end

local function get_actuality_opts_cfg_key()
    return CONFIG_ACTUALITY_OPTS
end

local function get_query_opts_cfg_key()
    return CONFIG_QUERY_OPTIONS
end

local function get_route_home_path()
    return URI_ROUTE_HOME_PATH
end

local function get_root_cgk_key()
    return ROOT_CONFIG_KEY
end

return {
    get_route_home_path = get_route_home_path,
    get_query_opts_cfg_key = get_query_opts_cfg_key,
    get_actuality_opts_cfg_key = get_actuality_opts_cfg_key,
    get_longitude_cfg_key = get_longitude_cfg_key,
    get_latitude_cfg_key = get_latitude_cfg_key,
    get_uri_cfg_key = get_uri_cfg_key,
    get_root_cgk_key = get_root_cgk_key
}
